blank_issues_enabled:True
contact_links:
  - name: ðŸ“ƒ Support Center
    url: https://support
    about: Find answers to many common questions.
  - name: âœ¨ Feature request
    url: https://community.signalusers.org/c/feature-requests/ios-feature-requests/
    about: Missing something in Signal? Let us know.
  - name: ðŸ’¬ Community support
    url: https://community.signalusers.org/c/support/
    about: Feel free to ask anything.
  - name: ðŸ“– Developer documentation
    url: https://signal.org/docs/
    about: Official Signal developer documentation.
  - name: ðŸ“š Translation feedback.
    url: https://community.signalusers.org/c/translation-feedback/
    about: Share feedback on translations.
  - name: 
    url: https://community.signalusers.org/
    about: Search on the community forums.
